contact_links:
  - name: 📚 Documentation
    url: http://ghouldev.me/PythonProtector/
    about: Before Making An Issue, Make Sure To Check The Documentation

  - name: 📚 Developer Documentation
    url: https://github.com/xFGhoul/Mai/blob/dev/.github/CONTRIBUTING.md
    about: Make Sure To Check The Developer Documentation If This Issue Is Focused On Code

  - name: 🤔 Support Question
    url: https://discord.gg/yMu9qjdrmp
    about: Ask Questions At Our Discord If The Documentation Was Not Of Any Help
